### ISSUE TITLE
Weird behaviour when a text option doesn't have a default value

### ISSUE THREAD

**Issue by fpringle** [poscat0x04/hinit#3]
When including an option in `template.toml` **without** a `default:` field, with `type:` set to `text`, I'm prompted for a `Bool`.

Steps to reproduce
------------------

1. Create a new template with 2 files:
```toml
# bug-test/template.toml
desc = "Template to test interactive bug"
ignores = []
tags = []

[[options]]
type = "text"
name = "myfield"
```

```txt
# bug-test/file.txt
{{ myfield }}
```

2. Run `hinit`

```bash
$ hi init bug-test bug-test
Please input the value of option
    myfield : Bool
(y/n)> 
```
This is weird, we're being prompted for a `Bool` even though we specified `myfield` is a `text`. Also:

3. Enter Y or N
```bash
Please input the value of option
    myfield : Bool
(y/n)> y
Error: failed to substitute the contents of file file.txt:
  • DirectlyRenderedValue False
```
